Correct broken references to variables
This was causing the following errors when in plan:

bash-5.0# terraform plan

Error: Reference to undeclared input variable

  on external-dns.tf line 6, in module "external_dns":
   6:   cluster_r53_domainfilters = lookup(var.cluster_r53_domainfilters, terraform.workspace, [data.terraform_remote_state.cluster.outputs.cluster_domain_name])

An input variable with the name "cluster_r53_domainfilters" has not been
declared. This variable can be declared with a variable
"cluster_r53_domainfilters" {} block.

Error: Reference to undeclared resource

  on external-dns.tf line 7, in module "external_dns":
   7:   hostzone                  = lookup(var.cluster_r53_resource_maps, terraform.workspace, [data.aws_route53_zone.selected.zone_id])

A data resource "aws_route53_zone" "selected" has not been declared in the
root module.

Error: Missing resource instance key

  on .terraform/modules/external_dns/kiam.tf line 18, in resource "aws_iam_role" "external_dns":
  18:   assume_role_policy = data.aws_iam_policy_document.external_dns_assume.json

Because data.aws_iam_policy_document.external_dns_assume has "count" set, its
attributes must be accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    data.aws_iam_policy_document.external_dns_assume[count.index]

Error: Reference to undeclared local value

  on .terraform/modules/external_dns/kiam.tf line 27, in data "aws_iam_policy_document" "external_dns":
  27:       terraform.workspace == local.live_workspace ? "*" : var.hostedzone,

A local value with the name "live_workspace" has not been declared.

Error: Reference to undeclared input variable

  on .terraform/modules/external_dns/kiam.tf line 27, in data "aws_iam_policy_document" "external_dns":
  27:       terraform.workspace == local.live_workspace ? "*" : var.hostedzone,

An input variable with the name "hostedzone" has not been declared. Did you
mean "hostzone"?